version: '3'
services:
  eva:
    build: .
    image: ${EVA_IMAGE}:${EVA_VERSION}
    command: gunicorn --workers 4 --max-requests=1000 --access-logfile - --error-logfile - --bind=0.0.0.0:8000 eva.wsgi:application
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    links:
      - redis
      - postgres
      - celery
    volumes:
      - static:/app/static
      - ${EVA_VOLUME}:/app/media
      
  celery:
    build: .
    image: ${EVA_IMAGE}:${EVA_VERSION}
    command: celery -A eva worker -l info
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    links:
      - redis
      - postgres
    volumes:
      - ${EVA_VOLUME}:/app/media
      
  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=eva_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
    volumes:
      - database:/var/lib/postgresql/data
      
volumes:
  static:
  database:
